id: IB542F547
ocr_import_info:
  timestamp: '2023-09-23T04:09:38.415782+00:00'
  batch_id: batch-ce09
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 04:19:13.069633+00:00
last_modified: 2023-09-23 04:19:13.069641+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4320
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4320
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་ས་བཅད་དྲི་མེད་ཤེལ་ཕྲེང་སོགས་གསར་རྙེད་ཐོད་བུའི་སྐོར།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9954697725016124
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN8558:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8558
      total_pages: 392
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN8558.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9954697725016124
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
